### ISSUE TITLE
UTF-8 encoded error

### ISSUE THREAD

**Issue by DaMexicanJustice** [edipetres/Depressed_Year#1]
When I attempt to webget your csv file, I get a csv document containing the following:
`Jupyter Notebook
current mode
File
Edit
View
Language

1
Error! /python_course/notebooks/programs/AviationDataset.csv is not UTF-8 encoded
2
Saving disabled.
3
See Console for more details.
`
What should I do to fix this?

**Comment by edipetres** [comment]
Hey, thanks for the find. Updated the url, so that now it gives the raw .csv document which you can webget.
Good luck ;)
